name: Terraform Azure Deploymentt
on:
  push:
    branches:
      - dev-branch
jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v2 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - name: Login Azure
        uses: azure/login@v1 
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Import Resource Group
         

 
        run: |
          terraform --version 
          terraform init
          terraform plan
          terraform destroy -auto-approve
          terraform show
